milon_demo_homepage:
    path:     /hello/{name}
    defaults: { _controller: MilonDemoBundle:Default:index }

milon_demo_newpage:
    path:     /agmination
    defaults: { _controller: MilonDemoBundle:Agmination:firstPage }